name: CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
        types: [closed]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 13
            - name: Install Vue CLI
              run: npm install -g @vue/cli
            - name: Install NPM Packages.
              run: npm install
            - name: Build VUE Files
              run: npm run build
            - name: Commit files
              run: |
                  cd dist
                  echo "hub.altv.mp" > CNAME
                  git init
                  git config --local user.email "{{ secrets.GH_MAIL }}"
                  git config --local user.name "{{ secrets.GH_USER }}"
                  git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/:user/:repo.git"
                  git add -A
                  git commit -m "Redeploy Website" -a
                  git push -f git@github.com:altmp/altv-hub-client.git master:gh-pages
